parameters:
    app.admin_menu:
      # - ["名称", "图标", "uri", "上级部门"]
        - ["root", "", "", "god"]
        - ["首页", "fa-solid fa-house", "/admin/index", "root"]
        - ["组织架构", "fa-solid fa-sitemap", "#", "root"]
        - ["二级目录", "", "#", "组织架构"]
        - ["成员与部门", "", "#", "二级目录"]
        - ["三级目录", "", "#", "二级目录"]
        - ["成员与部门", "", "#", "三级目录"]
        - ["角色管理", "", "#", "三级目录"]
        - ["单位管理", "", "#", "三级目录"]
        - ["四级目录", "", "#", "三级目录"]
        - ["成员与部门", "", "#", "四级目录"]
        - ["角色管理", "", "#", "四级目录"]
        - ["单位管理", "", "#", "四级目录"]
        - ["用户组管理", "", "#", "三级目录"]
        - ["成员字段管理", "", "#", "三级目录"]
        - ["成员与部门", "", "#", "二级目录"]
        - ["角色管理", "", "#", "二级目录"]
        - ["单位管理", "", "#", "二级目录"]
        - ["用户组管理", "", "#", "二级目录"]
        - ["成员字段管理", "", "#", "二级目录"]
        - ["关联组织", "", "#", "组织架构"]
        - ["成员与部门", "", "#", "组织架构"]
        - ["角色管理", "", "#", "组织架构"]
        - ["单位管理", "", "#", "组织架构"]
        - ["用户组管理", "", "#", "组织架构"]
        - ["成员字段管理", "", "#", "组织架构"]
        - ["关联组织", "", "#", "组织架构"]